site_name: QueryCat Documentation
nav:
  - 'Home': index.md
  - 'Tutorial': tutorial.md
  - 'Concepts': concepts.md
  - 'Plugins':
    - 'Logs': plugins/logs.md
  - 'Formatters': formatters.md
  - 'Commands':
    - 'ECHO': commands/echo.md
    - 'SELECT': commands/select.md
  - 'Input':
    - 'CSV': input/csv.md
    - 'JSON': input/json.md
    - 'STDIN': input/stdin.md
    - 'Text': input/text-line.md
    - 'TSV': input/tsv.md
  - 'Output':
    - 'CSV': output/csv.md
    - 'JSON': output/json.md
    - 'Text Table': output/text-table.md
    - 'TSV': output/tsv.md
  - 'Functions':
    - 'Aggregate': functions/aggregate.md
    - 'Crypto': functions/crypto.md
    - 'Date and Time': functions/datetime.md
    - 'Info': functions/info.md
    - 'Input': functions/input.md
    - 'Math': functions/math.md
    - 'Misc': functions/misc.md
    - 'Output': functions/output.md
    - 'String': functions/string.md
    - 'System': functions/system.md
  - 'FAQ': faq.md
  - 'Features':
    - 'Web Server': features/web-server.md
  - 'Development':
    - 'Overview': development/index.md
  - 'Misc':
    - 'Alternative Tools': misc/alternative-tools.md
theme: readthedocs
