site_name: QueryCat Documentation
site_author: Ivan Kozhin
nav:
  - 'Home': index.md
  - 'Tutorial': tutorial.md
  - 'Concepts': concepts.md
  - 'Plugins':
    - 'Overview': plugins/index.md
    - 'List': plugins/list.md
  - 'Formatters': formatters.md
  - 'Commands':
    - 'DECLARE': commands/declare.md
    - 'ECHO': commands/echo.md
    - 'INSERT': commands/insert.md
    - 'SELECT': commands/select.md
    - 'SET': commands/set.md
    - 'UPDATE': commands/update.md
  - 'Input':
    - 'CSV': input/csv.md
    - 'Grok': input/grok.md
    - 'IISW3C': input/iisw3c.md
    - 'JSON': input/json.md
    - 'RegEx': input/regex.md
    - 'STDIN': input/stdin.md
    - 'SUBRIP': input/subrip.md
    - 'Text': input/text-line.md
    - 'TSV': input/tsv.md
    - 'XML': input/xml.md
  - 'Output':
    - 'CSV': output/csv.md
    - 'JSON': output/json.md
    - 'Text Table': output/text-table.md
    - 'TSV': output/tsv.md
    - 'XML': output/xml.md
  - 'Functions':
    - 'Aggregate': functions/aggregate.md
    - 'Crypto': functions/crypto.md
    - 'Date and Time': functions/datetime.md
    - 'Info': functions/info.md
    - 'Input': functions/input.md
    - 'JSON': functions/json.md
    - 'Math': functions/math.md
    - 'Misc': functions/misc.md
    - 'Object': functions/object.md
    - 'Output': functions/output.md
    - 'String': functions/string.md
  - 'FAQ': faq.md
  - 'Features':
    - 'Web Server': features/web-server.md
  - 'Development':
    - 'Overview': development/index.md
    - 'Components': development/components.md
    - 'Functions': development/functions.md
    - 'Assembly': development/connector-assembly.md
    - 'Thrift': development/connector-thrift.md
    - 'Simple Plugin': development/plugin-simple.md
    - 'Advanced Plugin': development/plugin-advanced.md
  - 'Misc':
    - 'Alternative Tools': misc/alternative-tools.md
theme: readthedocs
exclude_docs: |
  internal
markdown_extensions:
  - pymdownx.superfences
