//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryCat.Backend.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("QueryCat.Backend.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CannotFindColumnOrVariable {
            get {
                return ResourceManager.GetString("CannotFindColumnOrVariable", resourceCulture);
            }
        }
        
        internal static string CannotApplyOperator {
            get {
                return ResourceManager.GetString("CannotApplyOperator", resourceCulture);
            }
        }
        
        internal static string InvalidUnionColumnsCount {
            get {
                return ResourceManager.GetString("InvalidUnionColumnsCount", resourceCulture);
            }
        }
        
        internal static string TypesMistmatch {
            get {
                return ResourceManager.GetString("TypesMistmatch", resourceCulture);
            }
        }
        
        internal static string CannotFindFunction {
            get {
                return ResourceManager.GetString("CannotFindFunction", resourceCulture);
            }
        }
        
        internal static string CannotFindFunctionWithArgs {
            get {
                return ResourceManager.GetString("CannotFindFunctionWithArgs", resourceCulture);
            }
        }
        
        internal static string FunctionMultipleSignatures {
            get {
                return ResourceManager.GetString("FunctionMultipleSignatures", resourceCulture);
            }
        }
        
        internal static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        internal static string InvalidRowsInputType {
            get {
                return ResourceManager.GetString("InvalidRowsInputType", resourceCulture);
            }
        }
        
        internal static string InvalidRowIndex {
            get {
                return ResourceManager.GetString("InvalidRowIndex", resourceCulture);
            }
        }
        
        internal static string InvalidBetweenExpression {
            get {
                return ResourceManager.GetString("InvalidBetweenExpression", resourceCulture);
            }
        }
        
        internal static string CannotSetArgument {
            get {
                return ResourceManager.GetString("CannotSetArgument", resourceCulture);
            }
        }
        
        internal static string CannotFindArgument {
            get {
                return ResourceManager.GetString("CannotFindArgument", resourceCulture);
            }
        }
        
        internal static string NoColumns {
            get {
                return ResourceManager.GetString("NoColumns", resourceCulture);
            }
        }
        
        internal static string InvalidSubqueryColumnsCount {
            get {
                return ResourceManager.GetString("InvalidSubqueryColumnsCount", resourceCulture);
            }
        }
        
        internal static string CannotProcessNodeAsInput {
            get {
                return ResourceManager.GetString("CannotProcessNodeAsInput", resourceCulture);
            }
        }
        
        internal static string CannotFindColumn {
            get {
                return ResourceManager.GetString("CannotFindColumn", resourceCulture);
            }
        }
        
        internal static string InvalidArgumentType {
            get {
                return ResourceManager.GetString("InvalidArgumentType", resourceCulture);
            }
        }
    }
}
