/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{

  public partial class ChatRequest : TBase
  {
    private string? _model;
    private List<global::QueryCat.Plugins.Sdk.ChatTool>? _tools;
    private Dictionary<string, global::QueryCat.Plugins.Sdk.VariantValue>? _options;

    public List<global::QueryCat.Plugins.Sdk.ChatMessage>? Messages { get; set; }

    public string Type { get; set; } = string.Empty;

    public string? Model
    {
      get
      {
        return _model;
      }
      set
      {
        __isset.@model = true;
        this._model = value;
      }
    }

    public List<global::QueryCat.Plugins.Sdk.ChatTool>? Tools
    {
      get
      {
        return _tools;
      }
      set
      {
        __isset.@tools = true;
        this._tools = value;
      }
    }

    public Dictionary<string, global::QueryCat.Plugins.Sdk.VariantValue>? Options
    {
      get
      {
        return _options;
      }
      set
      {
        __isset.@options = true;
        this._options = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool @model;
      public bool @tools;
      public bool @options;
    }

    public ChatRequest()
    {
    }

    public ChatRequest(List<global::QueryCat.Plugins.Sdk.ChatMessage>? @messages, string @type) : this()
    {
      this.Messages = @messages;
      this.Type = @type;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_messages = false;
        bool isset_type = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List)
              {
                {
                  var _list105 = await iprot.ReadListBeginAsync(cancellationToken);
                  Messages = new List<global::QueryCat.Plugins.Sdk.ChatMessage>(_list105.Count);
                  for(int _i106 = 0; _i106 < _list105.Count; ++_i106)
                  {
                    global::QueryCat.Plugins.Sdk.ChatMessage _elem107;
                    _elem107 = new global::QueryCat.Plugins.Sdk.ChatMessage();
                    await _elem107.ReadAsync(iprot, cancellationToken);
                    Messages.Add(_elem107);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_messages = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                Type = await iprot.ReadStringAsync(cancellationToken);
                isset_type = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.String)
              {
                Model = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.List)
              {
                {
                  var _list108 = await iprot.ReadListBeginAsync(cancellationToken);
                  Tools = new List<global::QueryCat.Plugins.Sdk.ChatTool>(_list108.Count);
                  for(int _i109 = 0; _i109 < _list108.Count; ++_i109)
                  {
                    global::QueryCat.Plugins.Sdk.ChatTool _elem110;
                    _elem110 = new global::QueryCat.Plugins.Sdk.ChatTool();
                    await _elem110.ReadAsync(iprot, cancellationToken);
                    Tools.Add(_elem110);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 5:
              if (field.Type == TType.Map)
              {
                {
                  var _map111 = await iprot.ReadMapBeginAsync(cancellationToken);
                  Options = new Dictionary<string, global::QueryCat.Plugins.Sdk.VariantValue>(_map111.Count);
                  for(int _i112 = 0; _i112 < _map111.Count; ++_i112)
                  {
                    string _key113;
                    global::QueryCat.Plugins.Sdk.VariantValue _val114;
                    _key113 = await iprot.ReadStringAsync(cancellationToken);
                    _val114 = new global::QueryCat.Plugins.Sdk.VariantValue();
                    await _val114.ReadAsync(iprot, cancellationToken);
                    Options[_key113] = _val114;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_messages)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_type)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp115 = new TStruct("ChatRequest");
        await oprot.WriteStructBeginAsync(tmp115, cancellationToken);
        #pragma warning disable IDE0017  // simplified init
        var tmp116 = new TField();
        if((Messages != null))
        {
          tmp116.Name = "messages";
          tmp116.Type = TType.List;
          tmp116.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp116, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Messages.Count), cancellationToken);
          foreach (global::QueryCat.Plugins.Sdk.ChatMessage _iter117 in Messages)
          {
            await _iter117.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Type != null))
        {
          tmp116.Name = "type";
          tmp116.Type = TType.String;
          tmp116.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp116, cancellationToken);
          await oprot.WriteStringAsync(Type, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Model != null) && __isset.@model)
        {
          tmp116.Name = "model";
          tmp116.Type = TType.String;
          tmp116.ID = 3;
          await oprot.WriteFieldBeginAsync(tmp116, cancellationToken);
          await oprot.WriteStringAsync(Model, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Tools != null) && __isset.@tools)
        {
          tmp116.Name = "tools";
          tmp116.Type = TType.List;
          tmp116.ID = 4;
          await oprot.WriteFieldBeginAsync(tmp116, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Tools.Count), cancellationToken);
          foreach (global::QueryCat.Plugins.Sdk.ChatTool _iter118 in Tools)
          {
            await _iter118.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Options != null) && __isset.@options)
        {
          tmp116.Name = "options";
          tmp116.Type = TType.Map;
          tmp116.ID = 5;
          await oprot.WriteFieldBeginAsync(tmp116, cancellationToken);
          await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.Struct, Options.Count), cancellationToken);
          foreach (string _iter119 in Options.Keys)
          {
            await oprot.WriteStringAsync(_iter119, cancellationToken);
            await Options[_iter119].WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteMapEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        #pragma warning restore IDE0017  // simplified init
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not ChatRequest other) return false;
      if (ReferenceEquals(this, other)) return true;
      return TCollections.Equals(Messages, other.Messages)
        && global::System.Object.Equals(Type, other.Type)
        && ((__isset.@model == other.__isset.@model) && ((!__isset.@model) || (global::System.Object.Equals(Model, other.Model))))
        && ((__isset.@tools == other.__isset.@tools) && ((!__isset.@tools) || (TCollections.Equals(Tools, other.Tools))))
        && ((__isset.@options == other.__isset.@options) && ((!__isset.@options) || (TCollections.Equals(Options, other.Options))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Messages != null))
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Messages);
        }
        if((Type != null))
        {
          hashcode = (hashcode * 397) + Type.GetHashCode();
        }
        if((Model != null) && __isset.@model)
        {
          hashcode = (hashcode * 397) + Model.GetHashCode();
        }
        if((Tools != null) && __isset.@tools)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Tools);
        }
        if((Options != null) && __isset.@options)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Options);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp120 = new StringBuilder("ChatRequest(");
      if((Messages != null))
      {
        tmp120.Append(", Messages: ");
        Messages.ToString(tmp120);
      }
      if((Type != null))
      {
        tmp120.Append(", Type: ");
        Type.ToString(tmp120);
      }
      if((Model != null) && __isset.@model)
      {
        tmp120.Append(", Model: ");
        Model.ToString(tmp120);
      }
      if((Tools != null) && __isset.@tools)
      {
        tmp120.Append(", Tools: ");
        Tools.ToString(tmp120);
      }
      if((Options != null) && __isset.@options)
      {
        tmp120.Append(", Options: ");
        Options.ToString(tmp120);
      }
      tmp120.Append(')');
      return tmp120.ToString();
    }
  }

}
