/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{

  public partial class ChatMessage : TBase
  {
    private List<global::QueryCat.Plugins.Sdk.ChatToolCall>? _tool_calls;
    private string? _tool_call_id;

    public string Content { get; set; } = string.Empty;

    public string Role { get; set; } = string.Empty;

    public List<global::QueryCat.Plugins.Sdk.ChatToolCall>? ToolCalls
    {
      get
      {
        return _tool_calls;
      }
      set
      {
        __isset.tool_calls = true;
        this._tool_calls = value;
      }
    }

    public string? ToolCallId
    {
      get
      {
        return _tool_call_id;
      }
      set
      {
        __isset.tool_call_id = true;
        this._tool_call_id = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool tool_calls;
      public bool tool_call_id;
    }

    public ChatMessage()
    {
    }

    public ChatMessage(string @content, string @role) : this()
    {
      this.Content = @content;
      this.Role = @role;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_content = false;
        bool isset_role = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                Content = await iprot.ReadStringAsync(cancellationToken);
                isset_content = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                Role = await iprot.ReadStringAsync(cancellationToken);
                isset_role = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.List)
              {
                {
                  var _list97 = await iprot.ReadListBeginAsync(cancellationToken);
                  ToolCalls = new List<global::QueryCat.Plugins.Sdk.ChatToolCall>(_list97.Count);
                  for(int _i98 = 0; _i98 < _list97.Count; ++_i98)
                  {
                    global::QueryCat.Plugins.Sdk.ChatToolCall _elem99;
                    _elem99 = new global::QueryCat.Plugins.Sdk.ChatToolCall();
                    await _elem99.ReadAsync(iprot, cancellationToken);
                    ToolCalls.Add(_elem99);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.String)
              {
                ToolCallId = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_content)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_role)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp100 = new TStruct("ChatMessage");
        await oprot.WriteStructBeginAsync(tmp100, cancellationToken);
        #pragma warning disable IDE0017  // simplified init
        var tmp101 = new TField();
        if((Content != null))
        {
          tmp101.Name = "content";
          tmp101.Type = TType.String;
          tmp101.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp101, cancellationToken);
          await oprot.WriteStringAsync(Content, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Role != null))
        {
          tmp101.Name = "role";
          tmp101.Type = TType.String;
          tmp101.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp101, cancellationToken);
          await oprot.WriteStringAsync(Role, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((ToolCalls != null) && __isset.tool_calls)
        {
          tmp101.Name = "tool_calls";
          tmp101.Type = TType.List;
          tmp101.ID = 3;
          await oprot.WriteFieldBeginAsync(tmp101, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.Struct, ToolCalls.Count), cancellationToken);
          foreach (global::QueryCat.Plugins.Sdk.ChatToolCall _iter102 in ToolCalls)
          {
            await _iter102.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((ToolCallId != null) && __isset.tool_call_id)
        {
          tmp101.Name = "tool_call_id";
          tmp101.Type = TType.String;
          tmp101.ID = 4;
          await oprot.WriteFieldBeginAsync(tmp101, cancellationToken);
          await oprot.WriteStringAsync(ToolCallId, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        #pragma warning restore IDE0017  // simplified init
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not ChatMessage other) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(Content, other.Content)
        && global::System.Object.Equals(Role, other.Role)
        && ((__isset.tool_calls == other.__isset.tool_calls) && ((!__isset.tool_calls) || (TCollections.Equals(ToolCalls, other.ToolCalls))))
        && ((__isset.tool_call_id == other.__isset.tool_call_id) && ((!__isset.tool_call_id) || (global::System.Object.Equals(ToolCallId, other.ToolCallId))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Content != null))
        {
          hashcode = (hashcode * 397) + Content.GetHashCode();
        }
        if((Role != null))
        {
          hashcode = (hashcode * 397) + Role.GetHashCode();
        }
        if((ToolCalls != null) && __isset.tool_calls)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(ToolCalls);
        }
        if((ToolCallId != null) && __isset.tool_call_id)
        {
          hashcode = (hashcode * 397) + ToolCallId.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp103 = new StringBuilder("ChatMessage(");
      if((Content != null))
      {
        tmp103.Append(", Content: ");
        Content.ToString(tmp103);
      }
      if((Role != null))
      {
        tmp103.Append(", Role: ");
        Role.ToString(tmp103);
      }
      if((ToolCalls != null) && __isset.tool_calls)
      {
        tmp103.Append(", ToolCalls: ");
        ToolCalls.ToString(tmp103);
      }
      if((ToolCallId != null) && __isset.tool_call_id)
      {
        tmp103.Append(", ToolCallId: ");
        ToolCallId.ToString(tmp103);
      }
      tmp103.Append(')');
      return tmp103.ToString();
    }
  }

}
