/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{

  public partial class ChatResponse : TBase
  {
    private string? _model;
    private string? _stop_reason;
    private Dictionary<string, global::QueryCat.Plugins.Sdk.VariantValue>? _metadata;

    public List<global::QueryCat.Plugins.Sdk.ChatMessage>? Messages { get; set; }

    public string MessageId { get; set; } = string.Empty;

    public string? Model
    {
      get
      {
        return _model;
      }
      set
      {
        __isset.@model = true;
        this._model = value;
      }
    }

    public string? StopReason
    {
      get
      {
        return _stop_reason;
      }
      set
      {
        __isset.stop_reason = true;
        this._stop_reason = value;
      }
    }

    public Dictionary<string, global::QueryCat.Plugins.Sdk.VariantValue>? Metadata
    {
      get
      {
        return _metadata;
      }
      set
      {
        __isset.@metadata = true;
        this._metadata = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool @model;
      public bool stop_reason;
      public bool @metadata;
    }

    public ChatResponse()
    {
    }

    public ChatResponse(List<global::QueryCat.Plugins.Sdk.ChatMessage>? @messages, string message_id) : this()
    {
      this.Messages = @messages;
      this.MessageId = message_id;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_messages = false;
        bool isset_message_id = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List)
              {
                {
                  var _list122 = await iprot.ReadListBeginAsync(cancellationToken);
                  Messages = new List<global::QueryCat.Plugins.Sdk.ChatMessage>(_list122.Count);
                  for(int _i123 = 0; _i123 < _list122.Count; ++_i123)
                  {
                    global::QueryCat.Plugins.Sdk.ChatMessage _elem124;
                    _elem124 = new global::QueryCat.Plugins.Sdk.ChatMessage();
                    await _elem124.ReadAsync(iprot, cancellationToken);
                    Messages.Add(_elem124);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_messages = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                MessageId = await iprot.ReadStringAsync(cancellationToken);
                isset_message_id = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.String)
              {
                Model = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.String)
              {
                StopReason = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 5:
              if (field.Type == TType.Map)
              {
                {
                  var _map125 = await iprot.ReadMapBeginAsync(cancellationToken);
                  Metadata = new Dictionary<string, global::QueryCat.Plugins.Sdk.VariantValue>(_map125.Count);
                  for(int _i126 = 0; _i126 < _map125.Count; ++_i126)
                  {
                    string _key127;
                    global::QueryCat.Plugins.Sdk.VariantValue _val128;
                    _key127 = await iprot.ReadStringAsync(cancellationToken);
                    _val128 = new global::QueryCat.Plugins.Sdk.VariantValue();
                    await _val128.ReadAsync(iprot, cancellationToken);
                    Metadata[_key127] = _val128;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_messages)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_message_id)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp129 = new TStruct("ChatResponse");
        await oprot.WriteStructBeginAsync(tmp129, cancellationToken);
        #pragma warning disable IDE0017  // simplified init
        var tmp130 = new TField();
        if((Messages != null))
        {
          tmp130.Name = "messages";
          tmp130.Type = TType.List;
          tmp130.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp130, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Messages.Count), cancellationToken);
          foreach (global::QueryCat.Plugins.Sdk.ChatMessage _iter131 in Messages)
          {
            await _iter131.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((MessageId != null))
        {
          tmp130.Name = "message_id";
          tmp130.Type = TType.String;
          tmp130.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp130, cancellationToken);
          await oprot.WriteStringAsync(MessageId, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Model != null) && __isset.@model)
        {
          tmp130.Name = "model";
          tmp130.Type = TType.String;
          tmp130.ID = 3;
          await oprot.WriteFieldBeginAsync(tmp130, cancellationToken);
          await oprot.WriteStringAsync(Model, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((StopReason != null) && __isset.stop_reason)
        {
          tmp130.Name = "stop_reason";
          tmp130.Type = TType.String;
          tmp130.ID = 4;
          await oprot.WriteFieldBeginAsync(tmp130, cancellationToken);
          await oprot.WriteStringAsync(StopReason, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Metadata != null) && __isset.@metadata)
        {
          tmp130.Name = "metadata";
          tmp130.Type = TType.Map;
          tmp130.ID = 5;
          await oprot.WriteFieldBeginAsync(tmp130, cancellationToken);
          await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.Struct, Metadata.Count), cancellationToken);
          foreach (string _iter132 in Metadata.Keys)
          {
            await oprot.WriteStringAsync(_iter132, cancellationToken);
            await Metadata[_iter132].WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteMapEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        #pragma warning restore IDE0017  // simplified init
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not ChatResponse other) return false;
      if (ReferenceEquals(this, other)) return true;
      return TCollections.Equals(Messages, other.Messages)
        && global::System.Object.Equals(MessageId, other.MessageId)
        && ((__isset.@model == other.__isset.@model) && ((!__isset.@model) || (global::System.Object.Equals(Model, other.Model))))
        && ((__isset.stop_reason == other.__isset.stop_reason) && ((!__isset.stop_reason) || (global::System.Object.Equals(StopReason, other.StopReason))))
        && ((__isset.@metadata == other.__isset.@metadata) && ((!__isset.@metadata) || (TCollections.Equals(Metadata, other.Metadata))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Messages != null))
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Messages);
        }
        if((MessageId != null))
        {
          hashcode = (hashcode * 397) + MessageId.GetHashCode();
        }
        if((Model != null) && __isset.@model)
        {
          hashcode = (hashcode * 397) + Model.GetHashCode();
        }
        if((StopReason != null) && __isset.stop_reason)
        {
          hashcode = (hashcode * 397) + StopReason.GetHashCode();
        }
        if((Metadata != null) && __isset.@metadata)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Metadata);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp133 = new StringBuilder("ChatResponse(");
      if((Messages != null))
      {
        tmp133.Append(", Messages: ");
        Messages.ToString(tmp133);
      }
      if((MessageId != null))
      {
        tmp133.Append(", MessageId: ");
        MessageId.ToString(tmp133);
      }
      if((Model != null) && __isset.@model)
      {
        tmp133.Append(", Model: ");
        Model.ToString(tmp133);
      }
      if((StopReason != null) && __isset.stop_reason)
      {
        tmp133.Append(", StopReason: ");
        StopReason.ToString(tmp133);
      }
      if((Metadata != null) && __isset.@metadata)
      {
        tmp133.Append(", Metadata: ");
        Metadata.ToString(tmp133);
      }
      tmp133.Append(')');
      return tmp133.ToString();
    }
  }

}
