/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{
  public enum DataType
  {
    @VOID = -1,
    @NULL = 0,
    INTEGER = 1,
    @STRING = 2,
    @FLOAT = 3,
    TIMESTAMP = 4,
    BOOLEAN = 5,
    NUMERIC = 6,
    INTERVAL = 7,
    BLOB = 8,
    @OBJECT = 40,
    @DYNAMIC = 41,
    ARRAY = 42,
    MAP = 43,
  }
}
