/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;

// targeting net 8
#if( !NET8_0_OR_GREATER)
#error Unexpected target platform. See 'thrift --help' for details.
#endif

// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{
  public enum ErrorType
  {
    SUCCESS = 0,
    GENERIC = 1,
    INVALID_OBJECT = 2,
    NOT_SUPPORTED = 3,
    @INTERNAL = 4,
    ARGUMENT = 5,
    INVALID_AUTH_TOKEN = 10,
    INVALID_FUNCTION = 11,
  }
}
