/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{

  public partial class FunctionCallArgumentsTypes : TBase
  {

    public Dictionary<string, global::QueryCat.Plugins.Sdk.DataType>? Named { get; set; }

    public Dictionary<int, global::QueryCat.Plugins.Sdk.DataType>? Positional { get; set; }

    public FunctionCallArgumentsTypes()
    {
    }

    public FunctionCallArgumentsTypes(Dictionary<string, global::QueryCat.Plugins.Sdk.DataType>? @named, Dictionary<int, global::QueryCat.Plugins.Sdk.DataType>? @positional) : this()
    {
      this.Named = @named;
      this.Positional = @positional;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_named = false;
        bool isset_positional = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Map)
              {
                {
                  var _map185 = await iprot.ReadMapBeginAsync(cancellationToken);
                  Named = new Dictionary<string, global::QueryCat.Plugins.Sdk.DataType>(_map185.Count);
                  for(int _i186 = 0; _i186 < _map185.Count; ++_i186)
                  {
                    string _key187;
                    global::QueryCat.Plugins.Sdk.DataType _val188;
                    _key187 = await iprot.ReadStringAsync(cancellationToken);
                    _val188 = (global::QueryCat.Plugins.Sdk.DataType)await iprot.ReadI32Async(cancellationToken);
                    Named[_key187] = _val188;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
                isset_named = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Map)
              {
                {
                  var _map189 = await iprot.ReadMapBeginAsync(cancellationToken);
                  Positional = new Dictionary<int, global::QueryCat.Plugins.Sdk.DataType>(_map189.Count);
                  for(int _i190 = 0; _i190 < _map189.Count; ++_i190)
                  {
                    int _key191;
                    global::QueryCat.Plugins.Sdk.DataType _val192;
                    _key191 = await iprot.ReadI32Async(cancellationToken);
                    _val192 = (global::QueryCat.Plugins.Sdk.DataType)await iprot.ReadI32Async(cancellationToken);
                    Positional[_key191] = _val192;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
                isset_positional = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_named)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_positional)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp193 = new TStruct("FunctionCallArgumentsTypes");
        await oprot.WriteStructBeginAsync(tmp193, cancellationToken);
        #pragma warning disable IDE0017  // simplified init
        var tmp194 = new TField();
        if((Named != null))
        {
          tmp194.Name = "named";
          tmp194.Type = TType.Map;
          tmp194.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp194, cancellationToken);
          await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.I32, Named.Count), cancellationToken);
          foreach (string _iter195 in Named.Keys)
          {
            await oprot.WriteStringAsync(_iter195, cancellationToken);
            await oprot.WriteI32Async((int)Named[_iter195], cancellationToken);
          }
          await oprot.WriteMapEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Positional != null))
        {
          tmp194.Name = "positional";
          tmp194.Type = TType.Map;
          tmp194.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp194, cancellationToken);
          await oprot.WriteMapBeginAsync(new TMap(TType.I32, TType.I32, Positional.Count), cancellationToken);
          foreach (int _iter196 in Positional.Keys)
          {
            await oprot.WriteI32Async(_iter196, cancellationToken);
            await oprot.WriteI32Async((int)Positional[_iter196], cancellationToken);
          }
          await oprot.WriteMapEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        #pragma warning restore IDE0017  // simplified init
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not FunctionCallArgumentsTypes other) return false;
      if (ReferenceEquals(this, other)) return true;
      return TCollections.Equals(Named, other.Named)
        && TCollections.Equals(Positional, other.Positional);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Named != null))
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Named);
        }
        if((Positional != null))
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Positional);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp197 = new StringBuilder("FunctionCallArgumentsTypes(");
      if((Named != null))
      {
        tmp197.Append(", Named: ");
        Named.ToString(tmp197);
      }
      if((Positional != null))
      {
        tmp197.Append(", Positional: ");
        Positional.ToString(tmp197);
      }
      tmp197.Append(')');
      return tmp197.ToString();
    }
  }

}
