/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{

  public partial class FunctionCallArgumentsTypes : TBase
  {

    public Dictionary<string, global::QueryCat.Plugins.Sdk.DataType>? Named { get; set; }

    public Dictionary<int, global::QueryCat.Plugins.Sdk.DataType>? Positional { get; set; }

    public FunctionCallArgumentsTypes()
    {
    }

    public FunctionCallArgumentsTypes(Dictionary<string, global::QueryCat.Plugins.Sdk.DataType>? @named, Dictionary<int, global::QueryCat.Plugins.Sdk.DataType>? @positional) : this()
    {
      this.Named = @named;
      this.Positional = @positional;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_named = false;
        bool isset_positional = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Map)
              {
                {
                  var _map155 = await iprot.ReadMapBeginAsync(cancellationToken);
                  Named = new Dictionary<string, global::QueryCat.Plugins.Sdk.DataType>(_map155.Count);
                  for(int _i156 = 0; _i156 < _map155.Count; ++_i156)
                  {
                    string _key157;
                    global::QueryCat.Plugins.Sdk.DataType _val158;
                    _key157 = await iprot.ReadStringAsync(cancellationToken);
                    _val158 = (global::QueryCat.Plugins.Sdk.DataType)await iprot.ReadI32Async(cancellationToken);
                    Named[_key157] = _val158;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
                isset_named = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Map)
              {
                {
                  var _map159 = await iprot.ReadMapBeginAsync(cancellationToken);
                  Positional = new Dictionary<int, global::QueryCat.Plugins.Sdk.DataType>(_map159.Count);
                  for(int _i160 = 0; _i160 < _map159.Count; ++_i160)
                  {
                    int _key161;
                    global::QueryCat.Plugins.Sdk.DataType _val162;
                    _key161 = await iprot.ReadI32Async(cancellationToken);
                    _val162 = (global::QueryCat.Plugins.Sdk.DataType)await iprot.ReadI32Async(cancellationToken);
                    Positional[_key161] = _val162;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
                isset_positional = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_named)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_positional)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp163 = new TStruct("FunctionCallArgumentsTypes");
        await oprot.WriteStructBeginAsync(tmp163, cancellationToken);
        #pragma warning disable IDE0017  // simplified init
        var tmp164 = new TField();
        if((Named != null))
        {
          tmp164.Name = "named";
          tmp164.Type = TType.Map;
          tmp164.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp164, cancellationToken);
          await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.I32, Named.Count), cancellationToken);
          foreach (string _iter165 in Named.Keys)
          {
            await oprot.WriteStringAsync(_iter165, cancellationToken);
            await oprot.WriteI32Async((int)Named[_iter165], cancellationToken);
          }
          await oprot.WriteMapEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Positional != null))
        {
          tmp164.Name = "positional";
          tmp164.Type = TType.Map;
          tmp164.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp164, cancellationToken);
          await oprot.WriteMapBeginAsync(new TMap(TType.I32, TType.I32, Positional.Count), cancellationToken);
          foreach (int _iter166 in Positional.Keys)
          {
            await oprot.WriteI32Async(_iter166, cancellationToken);
            await oprot.WriteI32Async((int)Positional[_iter166], cancellationToken);
          }
          await oprot.WriteMapEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        #pragma warning restore IDE0017  // simplified init
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not FunctionCallArgumentsTypes other) return false;
      if (ReferenceEquals(this, other)) return true;
      return TCollections.Equals(Named, other.Named)
        && TCollections.Equals(Positional, other.Positional);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Named != null))
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Named);
        }
        if((Positional != null))
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Positional);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp167 = new StringBuilder("FunctionCallArgumentsTypes(");
      if((Named != null))
      {
        tmp167.Append(", Named: ");
        Named.ToString(tmp167);
      }
      if((Positional != null))
      {
        tmp167.Append(", Positional: ");
        Positional.ToString(tmp167);
      }
      tmp167.Append(')');
      return tmp167.ToString();
    }
  }

}
