/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{

  public partial class FunctionCallArguments : TBase
  {

    public Dictionary<string, global::QueryCat.Plugins.Sdk.VariantValue>? Named { get; set; }

    public List<global::QueryCat.Plugins.Sdk.VariantValue>? Positional { get; set; }

    public FunctionCallArguments()
    {
    }

    public FunctionCallArguments(Dictionary<string, global::QueryCat.Plugins.Sdk.VariantValue>? @named, List<global::QueryCat.Plugins.Sdk.VariantValue>? @positional) : this()
    {
      this.Named = @named;
      this.Positional = @positional;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_named = false;
        bool isset_positional = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Map)
              {
                {
                  var _map134 = await iprot.ReadMapBeginAsync(cancellationToken);
                  Named = new Dictionary<string, global::QueryCat.Plugins.Sdk.VariantValue>(_map134.Count);
                  for(int _i135 = 0; _i135 < _map134.Count; ++_i135)
                  {
                    string _key136;
                    global::QueryCat.Plugins.Sdk.VariantValue _val137;
                    _key136 = await iprot.ReadStringAsync(cancellationToken);
                    _val137 = new global::QueryCat.Plugins.Sdk.VariantValue();
                    await _val137.ReadAsync(iprot, cancellationToken);
                    Named[_key136] = _val137;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
                isset_named = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.List)
              {
                {
                  var _list138 = await iprot.ReadListBeginAsync(cancellationToken);
                  Positional = new List<global::QueryCat.Plugins.Sdk.VariantValue>(_list138.Count);
                  for(int _i139 = 0; _i139 < _list138.Count; ++_i139)
                  {
                    global::QueryCat.Plugins.Sdk.VariantValue _elem140;
                    _elem140 = new global::QueryCat.Plugins.Sdk.VariantValue();
                    await _elem140.ReadAsync(iprot, cancellationToken);
                    Positional.Add(_elem140);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_positional = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_named)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_positional)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp141 = new TStruct("FunctionCallArguments");
        await oprot.WriteStructBeginAsync(tmp141, cancellationToken);
        #pragma warning disable IDE0017  // simplified init
        var tmp142 = new TField();
        if((Named != null))
        {
          tmp142.Name = "named";
          tmp142.Type = TType.Map;
          tmp142.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp142, cancellationToken);
          await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.Struct, Named.Count), cancellationToken);
          foreach (string _iter143 in Named.Keys)
          {
            await oprot.WriteStringAsync(_iter143, cancellationToken);
            await Named[_iter143].WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteMapEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Positional != null))
        {
          tmp142.Name = "positional";
          tmp142.Type = TType.List;
          tmp142.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp142, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Positional.Count), cancellationToken);
          foreach (global::QueryCat.Plugins.Sdk.VariantValue _iter144 in Positional)
          {
            await _iter144.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        #pragma warning restore IDE0017  // simplified init
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not FunctionCallArguments other) return false;
      if (ReferenceEquals(this, other)) return true;
      return TCollections.Equals(Named, other.Named)
        && TCollections.Equals(Positional, other.Positional);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Named != null))
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Named);
        }
        if((Positional != null))
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Positional);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp145 = new StringBuilder("FunctionCallArguments(");
      if((Named != null))
      {
        tmp145.Append(", Named: ");
        Named.ToString(tmp145);
      }
      if((Positional != null))
      {
        tmp145.Append(", Positional: ");
        Positional.ToString(tmp145);
      }
      tmp145.Append(')');
      return tmp145.ToString();
    }
  }

}
