/**
 * Autogenerated by Thrift Compiler (0.18.1)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{

  public partial class KeyColumn : TBase
  {

    public string Name { get; set; } = string.Empty;

    public bool IsRequired { get; set; } = false;

    public List<string>? Operations { get; set; }

    public KeyColumn()
    {
    }

    public KeyColumn(string name, bool is_required, List<string>? operations) : this()
    {
      this.Name = name;
      this.IsRequired = is_required;
      this.Operations = operations;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_name = false;
        bool isset_is_required = false;
        bool isset_operations = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                Name = await iprot.ReadStringAsync(cancellationToken);
                isset_name = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Bool)
              {
                IsRequired = await iprot.ReadBoolAsync(cancellationToken);
                isset_is_required = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.List)
              {
                {
                  var _list36 = await iprot.ReadListBeginAsync(cancellationToken);
                  Operations = new List<string>(_list36.Count);
                  for(int _i37 = 0; _i37 < _list36.Count; ++_i37)
                  {
                    string _elem38;
                    _elem38 = await iprot.ReadStringAsync(cancellationToken);
                    Operations.Add(_elem38);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_operations = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_name)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_is_required)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_operations)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp39 = new TStruct("KeyColumn");
        await oprot.WriteStructBeginAsync(tmp39, cancellationToken);
        var tmp40 = new TField();
        if((Name != null))
        {
          tmp40.Name = "name";
          tmp40.Type = TType.String;
          tmp40.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp40, cancellationToken);
          await oprot.WriteStringAsync(Name, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        tmp40.Name = "is_required";
        tmp40.Type = TType.Bool;
        tmp40.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp40, cancellationToken);
        await oprot.WriteBoolAsync(IsRequired, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        if((Operations != null))
        {
          tmp40.Name = "operations";
          tmp40.Type = TType.List;
          tmp40.ID = 3;
          await oprot.WriteFieldBeginAsync(tmp40, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.String, Operations.Count), cancellationToken);
          foreach (string _iter41 in Operations)
          {
            await oprot.WriteStringAsync(_iter41, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not KeyColumn other) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(Name, other.Name)
        && global::System.Object.Equals(IsRequired, other.IsRequired)
        && TCollections.Equals(Operations, other.Operations);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Name != null))
        {
          hashcode = (hashcode * 397) + Name.GetHashCode();
        }
        hashcode = (hashcode * 397) + IsRequired.GetHashCode();
        if((Operations != null))
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Operations);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp42 = new StringBuilder("KeyColumn(");
      if((Name != null))
      {
        tmp42.Append(", Name: ");
        Name.ToString(tmp42);
      }
      tmp42.Append(", IsRequired: ");
      IsRequired.ToString(tmp42);
      if((Operations != null))
      {
        tmp42.Append(", Operations: ");
        Operations.ToString(tmp42);
      }
      tmp42.Append(')');
      return tmp42.ToString();
    }
  }

}
