/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{

  public partial class PluginData : TBase
  {
    private Dictionary<string, global::QueryCat.Plugins.Sdk.VariantValue>? _metadata;

    public List<global::QueryCat.Plugins.Sdk.Function>? Functions { get; set; }

    public string Name { get; set; } = string.Empty;

    public string Version { get; set; } = string.Empty;

    public Dictionary<string, global::QueryCat.Plugins.Sdk.VariantValue>? Metadata
    {
      get
      {
        return _metadata;
      }
      set
      {
        __isset.@metadata = true;
        this._metadata = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool @metadata;
    }

    public PluginData()
    {
    }

    public PluginData(List<global::QueryCat.Plugins.Sdk.Function>? @functions, string @name, string @version) : this()
    {
      this.Functions = @functions;
      this.Name = @name;
      this.Version = @version;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_functions = false;
        bool isset_name = false;
        bool isset_version = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List)
              {
                {
                  var _list33 = await iprot.ReadListBeginAsync(cancellationToken);
                  Functions = new List<global::QueryCat.Plugins.Sdk.Function>(_list33.Count);
                  for(int _i34 = 0; _i34 < _list33.Count; ++_i34)
                  {
                    global::QueryCat.Plugins.Sdk.Function _elem35;
                    _elem35 = new global::QueryCat.Plugins.Sdk.Function();
                    await _elem35.ReadAsync(iprot, cancellationToken);
                    Functions.Add(_elem35);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_functions = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                Name = await iprot.ReadStringAsync(cancellationToken);
                isset_name = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.String)
              {
                Version = await iprot.ReadStringAsync(cancellationToken);
                isset_version = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.Map)
              {
                {
                  var _map36 = await iprot.ReadMapBeginAsync(cancellationToken);
                  Metadata = new Dictionary<string, global::QueryCat.Plugins.Sdk.VariantValue>(_map36.Count);
                  for(int _i37 = 0; _i37 < _map36.Count; ++_i37)
                  {
                    string _key38;
                    global::QueryCat.Plugins.Sdk.VariantValue _val39;
                    _key38 = await iprot.ReadStringAsync(cancellationToken);
                    _val39 = new global::QueryCat.Plugins.Sdk.VariantValue();
                    await _val39.ReadAsync(iprot, cancellationToken);
                    Metadata[_key38] = _val39;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_functions)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_name)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_version)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp40 = new TStruct("PluginData");
        await oprot.WriteStructBeginAsync(tmp40, cancellationToken);
        #pragma warning disable IDE0017  // simplified init
        var tmp41 = new TField();
        if((Functions != null))
        {
          tmp41.Name = "functions";
          tmp41.Type = TType.List;
          tmp41.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp41, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Functions.Count), cancellationToken);
          foreach (global::QueryCat.Plugins.Sdk.Function _iter42 in Functions)
          {
            await _iter42.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Name != null))
        {
          tmp41.Name = "name";
          tmp41.Type = TType.String;
          tmp41.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp41, cancellationToken);
          await oprot.WriteStringAsync(Name, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Version != null))
        {
          tmp41.Name = "version";
          tmp41.Type = TType.String;
          tmp41.ID = 3;
          await oprot.WriteFieldBeginAsync(tmp41, cancellationToken);
          await oprot.WriteStringAsync(Version, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Metadata != null) && __isset.@metadata)
        {
          tmp41.Name = "metadata";
          tmp41.Type = TType.Map;
          tmp41.ID = 4;
          await oprot.WriteFieldBeginAsync(tmp41, cancellationToken);
          await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.Struct, Metadata.Count), cancellationToken);
          foreach (string _iter43 in Metadata.Keys)
          {
            await oprot.WriteStringAsync(_iter43, cancellationToken);
            await Metadata[_iter43].WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteMapEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        #pragma warning restore IDE0017  // simplified init
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not PluginData other) return false;
      if (ReferenceEquals(this, other)) return true;
      return TCollections.Equals(Functions, other.Functions)
        && global::System.Object.Equals(Name, other.Name)
        && global::System.Object.Equals(Version, other.Version)
        && ((__isset.@metadata == other.__isset.@metadata) && ((!__isset.@metadata) || (TCollections.Equals(Metadata, other.Metadata))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Functions != null))
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Functions);
        }
        if((Name != null))
        {
          hashcode = (hashcode * 397) + Name.GetHashCode();
        }
        if((Version != null))
        {
          hashcode = (hashcode * 397) + Version.GetHashCode();
        }
        if((Metadata != null) && __isset.@metadata)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Metadata);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp44 = new StringBuilder("PluginData(");
      if((Functions != null))
      {
        tmp44.Append(", Functions: ");
        Functions.ToString(tmp44);
      }
      if((Name != null))
      {
        tmp44.Append(", Name: ");
        Name.ToString(tmp44);
      }
      if((Version != null))
      {
        tmp44.Append(", Version: ");
        Version.ToString(tmp44);
      }
      if((Metadata != null) && __isset.@metadata)
      {
        tmp44.Append(", Metadata: ");
        Metadata.ToString(tmp44);
      }
      tmp44.Append(')');
      return tmp44.ToString();
    }
  }

}
