/**
 * Autogenerated by Thrift Compiler (0.18.1)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{

  public partial class QueryCatPluginException : TException, TBase
  {
    private int _object_handle;

    /// <summary>
    /// 
    /// <seealso cref="global::QueryCat.Plugins.Sdk.ErrorType"/>
    /// </summary>
    public global::QueryCat.Plugins.Sdk.ErrorType Type { get; set; } = default;

    public string ErrorMessage { get; set; } = string.Empty;

    public int ObjectHandle
    {
      get
      {
        return _object_handle;
      }
      set
      {
        __isset.object_handle = true;
        this._object_handle = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool object_handle;
    }

    public QueryCatPluginException()
    {
    }

    public QueryCatPluginException(global::QueryCat.Plugins.Sdk.ErrorType type, string error_message) : this()
    {
      this.Type = type;
      this.ErrorMessage = error_message;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_type = false;
        bool isset_error_message = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32)
              {
                Type = (global::QueryCat.Plugins.Sdk.ErrorType)await iprot.ReadI32Async(cancellationToken);
                isset_type = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                ErrorMessage = await iprot.ReadStringAsync(cancellationToken);
                isset_error_message = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.I32)
              {
                ObjectHandle = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_type)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_error_message)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp12 = new TStruct("QueryCatPluginException");
        await oprot.WriteStructBeginAsync(tmp12, cancellationToken);
        var tmp13 = new TField();
        tmp13.Name = "type";
        tmp13.Type = TType.I32;
        tmp13.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp13, cancellationToken);
        await oprot.WriteI32Async((int)Type, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        if((ErrorMessage != null))
        {
          tmp13.Name = "error_message";
          tmp13.Type = TType.String;
          tmp13.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp13, cancellationToken);
          await oprot.WriteStringAsync(ErrorMessage, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.object_handle)
        {
          tmp13.Name = "object_handle";
          tmp13.Type = TType.I32;
          tmp13.ID = 3;
          await oprot.WriteFieldBeginAsync(tmp13, cancellationToken);
          await oprot.WriteI32Async(ObjectHandle, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not QueryCatPluginException other) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(Type, other.Type)
        && global::System.Object.Equals(ErrorMessage, other.ErrorMessage)
        && ((__isset.object_handle == other.__isset.object_handle) && ((!__isset.object_handle) || (global::System.Object.Equals(ObjectHandle, other.ObjectHandle))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        hashcode = (hashcode * 397) + Type.GetHashCode();
        if((ErrorMessage != null))
        {
          hashcode = (hashcode * 397) + ErrorMessage.GetHashCode();
        }
        if(__isset.object_handle)
        {
          hashcode = (hashcode * 397) + ObjectHandle.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp14 = new StringBuilder("QueryCatPluginException(");
      tmp14.Append(", Type: ");
      Type.ToString(tmp14);
      if((ErrorMessage != null))
      {
        tmp14.Append(", ErrorMessage: ");
        ErrorMessage.ToString(tmp14);
      }
      if(__isset.object_handle)
      {
        tmp14.Append(", ObjectHandle: ");
        ObjectHandle.ToString(tmp14);
      }
      tmp14.Append(')');
      return tmp14.ToString();
    }
  }

}
