/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{

  public partial class RowsList : TBase
  {

    public bool HasMore { get; set; } = false;

    public List<global::QueryCat.Plugins.Sdk.VariantValue>? Values { get; set; }

    public RowsList()
    {
    }

    public RowsList(bool has_more, List<global::QueryCat.Plugins.Sdk.VariantValue>? @values) : this()
    {
      this.HasMore = has_more;
      this.Values = @values;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_has_more = false;
        bool isset_values = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Bool)
              {
                HasMore = await iprot.ReadBoolAsync(cancellationToken);
                isset_has_more = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.List)
              {
                {
                  var _list114 = await iprot.ReadListBeginAsync(cancellationToken);
                  Values = new List<global::QueryCat.Plugins.Sdk.VariantValue>(_list114.Count);
                  for(int _i115 = 0; _i115 < _list114.Count; ++_i115)
                  {
                    global::QueryCat.Plugins.Sdk.VariantValue _elem116;
                    _elem116 = new global::QueryCat.Plugins.Sdk.VariantValue();
                    await _elem116.ReadAsync(iprot, cancellationToken);
                    Values.Add(_elem116);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_values = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_has_more)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_values)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp117 = new TStruct("RowsList");
        await oprot.WriteStructBeginAsync(tmp117, cancellationToken);
        #pragma warning disable IDE0017  // simplified init
        var tmp118 = new TField();
        tmp118.Name = "has_more";
        tmp118.Type = TType.Bool;
        tmp118.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp118, cancellationToken);
        await oprot.WriteBoolAsync(HasMore, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        if((Values != null))
        {
          tmp118.Name = "values";
          tmp118.Type = TType.List;
          tmp118.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp118, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Values.Count), cancellationToken);
          foreach (global::QueryCat.Plugins.Sdk.VariantValue _iter119 in Values)
          {
            await _iter119.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        #pragma warning restore IDE0017  // simplified init
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not RowsList other) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(HasMore, other.HasMore)
        && TCollections.Equals(Values, other.Values);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        hashcode = (hashcode * 397) + HasMore.GetHashCode();
        if((Values != null))
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Values);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp120 = new StringBuilder("RowsList(");
      tmp120.Append(", HasMore: ");
      HasMore.ToString(tmp120);
      if((Values != null))
      {
        tmp120.Append(", Values: ");
        Values.ToString(tmp120);
      }
      tmp120.Append(')');
      return tmp120.ToString();
    }
  }

}
