/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{

  public partial class ScopeVariable : TBase
  {

    public string Name { get; set; } = string.Empty;

    public global::QueryCat.Plugins.Sdk.VariantValue? Value { get; set; }

    public ScopeVariable()
    {
    }

    public ScopeVariable(string @name, global::QueryCat.Plugins.Sdk.VariantValue? @value) : this()
    {
      this.Name = @name;
      this.Value = @value;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_name = false;
        bool isset_value = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                Name = await iprot.ReadStringAsync(cancellationToken);
                isset_name = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Struct)
              {
                Value = new global::QueryCat.Plugins.Sdk.VariantValue();
                await Value.ReadAsync(iprot, cancellationToken);
                isset_value = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_name)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_value)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp54 = new TStruct("ScopeVariable");
        await oprot.WriteStructBeginAsync(tmp54, cancellationToken);
        #pragma warning disable IDE0017  // simplified init
        var tmp55 = new TField();
        if((Name != null))
        {
          tmp55.Name = "name";
          tmp55.Type = TType.String;
          tmp55.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp55, cancellationToken);
          await oprot.WriteStringAsync(Name, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Value != null))
        {
          tmp55.Name = "value";
          tmp55.Type = TType.Struct;
          tmp55.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp55, cancellationToken);
          await Value.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        #pragma warning restore IDE0017  // simplified init
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not ScopeVariable other) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(Name, other.Name)
        && global::System.Object.Equals(Value, other.Value);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Name != null))
        {
          hashcode = (hashcode * 397) + Name.GetHashCode();
        }
        if((Value != null))
        {
          hashcode = (hashcode * 397) + Value.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp56 = new StringBuilder("ScopeVariable(");
      if((Name != null))
      {
        tmp56.Append(", Name: ");
        Name.ToString(tmp56);
      }
      if((Value != null))
      {
        tmp56.Append(", Value: ");
        Value.ToString(tmp56);
      }
      tmp56.Append(')');
      return tmp56.ToString();
    }
  }

}
