/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{

  public partial class Statistic : TBase
  {

    public long ExecutionTimeMs { get; set; } = 0;

    public long ProcessedCount { get; set; } = 0;

    public long ErrorsCount { get; set; } = 0;

    public List<global::QueryCat.Plugins.Sdk.StatisticRowError>? Errors { get; set; }

    public Statistic()
    {
    }

    public Statistic(long execution_time_ms, long processed_count, long errors_count, List<global::QueryCat.Plugins.Sdk.StatisticRowError>? @errors) : this()
    {
      this.ExecutionTimeMs = execution_time_ms;
      this.ProcessedCount = processed_count;
      this.ErrorsCount = errors_count;
      this.Errors = @errors;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_execution_time_ms = false;
        bool isset_processed_count = false;
        bool isset_errors_count = false;
        bool isset_errors = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I64)
              {
                ExecutionTimeMs = await iprot.ReadI64Async(cancellationToken);
                isset_execution_time_ms = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I64)
              {
                ProcessedCount = await iprot.ReadI64Async(cancellationToken);
                isset_processed_count = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.I64)
              {
                ErrorsCount = await iprot.ReadI64Async(cancellationToken);
                isset_errors_count = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.List)
              {
                {
                  var _list77 = await iprot.ReadListBeginAsync(cancellationToken);
                  Errors = new List<global::QueryCat.Plugins.Sdk.StatisticRowError>(_list77.Count);
                  for(int _i78 = 0; _i78 < _list77.Count; ++_i78)
                  {
                    global::QueryCat.Plugins.Sdk.StatisticRowError _elem79;
                    _elem79 = new global::QueryCat.Plugins.Sdk.StatisticRowError();
                    await _elem79.ReadAsync(iprot, cancellationToken);
                    Errors.Add(_elem79);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_errors = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_execution_time_ms)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_processed_count)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_errors_count)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_errors)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp80 = new TStruct("Statistic");
        await oprot.WriteStructBeginAsync(tmp80, cancellationToken);
        #pragma warning disable IDE0017  // simplified init
        var tmp81 = new TField();
        tmp81.Name = "execution_time_ms";
        tmp81.Type = TType.I64;
        tmp81.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp81, cancellationToken);
        await oprot.WriteI64Async(ExecutionTimeMs, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        tmp81.Name = "processed_count";
        tmp81.Type = TType.I64;
        tmp81.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp81, cancellationToken);
        await oprot.WriteI64Async(ProcessedCount, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        tmp81.Name = "errors_count";
        tmp81.Type = TType.I64;
        tmp81.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp81, cancellationToken);
        await oprot.WriteI64Async(ErrorsCount, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        if((Errors != null))
        {
          tmp81.Name = "errors";
          tmp81.Type = TType.List;
          tmp81.ID = 4;
          await oprot.WriteFieldBeginAsync(tmp81, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Errors.Count), cancellationToken);
          foreach (global::QueryCat.Plugins.Sdk.StatisticRowError _iter82 in Errors)
          {
            await _iter82.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        #pragma warning restore IDE0017  // simplified init
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not Statistic other) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(ExecutionTimeMs, other.ExecutionTimeMs)
        && global::System.Object.Equals(ProcessedCount, other.ProcessedCount)
        && global::System.Object.Equals(ErrorsCount, other.ErrorsCount)
        && TCollections.Equals(Errors, other.Errors);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        hashcode = (hashcode * 397) + ExecutionTimeMs.GetHashCode();
        hashcode = (hashcode * 397) + ProcessedCount.GetHashCode();
        hashcode = (hashcode * 397) + ErrorsCount.GetHashCode();
        if((Errors != null))
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Errors);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp83 = new StringBuilder("Statistic(");
      tmp83.Append(", ExecutionTimeMs: ");
      ExecutionTimeMs.ToString(tmp83);
      tmp83.Append(", ProcessedCount: ");
      ProcessedCount.ToString(tmp83);
      tmp83.Append(", ErrorsCount: ");
      ErrorsCount.ToString(tmp83);
      if((Errors != null))
      {
        tmp83.Append(", Errors: ");
        Errors.ToString(tmp83);
      }
      tmp83.Append(')');
      return tmp83.ToString();
    }
  }

}
