/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


// Thrift code generated for net8
#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace QueryCat.Plugins.Sdk
{

  public partial class VariantValue : TBase
  {
    private bool _isNull;
    private long _integer;
    private string? _string;
    private double _float;
    private long _timestamp;
    private bool _boolean;
    private global::QueryCat.Plugins.Sdk.DecimalValue? _decimal;
    private long _interval;
    private global::QueryCat.Plugins.Sdk.ObjectValue? _object;
    private string? _json;
    private List<global::QueryCat.Plugins.Sdk.VariantValue>? _array;
    private List<global::QueryCat.Plugins.Sdk.MapEntry>? _map;

    public bool IsNull
    {
      get
      {
        return _isNull;
      }
      set
      {
        __isset.isNull = true;
        this._isNull = value;
      }
    }

    public long Integer
    {
      get
      {
        return _integer;
      }
      set
      {
        __isset.@integer = true;
        this._integer = value;
      }
    }

    public string? String
    {
      get
      {
        return _string;
      }
      set
      {
        __isset.@string = true;
        this._string = value;
      }
    }

    public double Float
    {
      get
      {
        return _float;
      }
      set
      {
        __isset.@float = true;
        this._float = value;
      }
    }

    public long Timestamp
    {
      get
      {
        return _timestamp;
      }
      set
      {
        __isset.@timestamp = true;
        this._timestamp = value;
      }
    }

    public bool Boolean
    {
      get
      {
        return _boolean;
      }
      set
      {
        __isset.@boolean = true;
        this._boolean = value;
      }
    }

    public global::QueryCat.Plugins.Sdk.DecimalValue? Decimal
    {
      get
      {
        return _decimal;
      }
      set
      {
        __isset.@decimal = true;
        this._decimal = value;
      }
    }

    public long Interval
    {
      get
      {
        return _interval;
      }
      set
      {
        __isset.@interval = true;
        this._interval = value;
      }
    }

    public global::QueryCat.Plugins.Sdk.ObjectValue? Object
    {
      get
      {
        return _object;
      }
      set
      {
        __isset.@object = true;
        this._object = value;
      }
    }

    public string? Json
    {
      get
      {
        return _json;
      }
      set
      {
        __isset.@json = true;
        this._json = value;
      }
    }

    public List<global::QueryCat.Plugins.Sdk.VariantValue>? Array
    {
      get
      {
        return _array;
      }
      set
      {
        __isset.@array = true;
        this._array = value;
      }
    }

    public List<global::QueryCat.Plugins.Sdk.MapEntry>? Map
    {
      get
      {
        return _map;
      }
      set
      {
        __isset.@map = true;
        this._map = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool isNull;
      public bool @integer;
      public bool @string;
      public bool @float;
      public bool @timestamp;
      public bool @boolean;
      public bool @decimal;
      public bool @interval;
      public bool @object;
      public bool @json;
      public bool @array;
      public bool @map;
    }

    public VariantValue()
    {
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Bool)
              {
                IsNull = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I64)
              {
                Integer = await iprot.ReadI64Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.String)
              {
                String = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.Double)
              {
                Float = await iprot.ReadDoubleAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 5:
              if (field.Type == TType.I64)
              {
                Timestamp = await iprot.ReadI64Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 6:
              if (field.Type == TType.Bool)
              {
                Boolean = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 7:
              if (field.Type == TType.Struct)
              {
                Decimal = new global::QueryCat.Plugins.Sdk.DecimalValue();
                await Decimal.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 8:
              if (field.Type == TType.I64)
              {
                Interval = await iprot.ReadI64Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 9:
              if (field.Type == TType.Struct)
              {
                Object = new global::QueryCat.Plugins.Sdk.ObjectValue();
                await Object.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 10:
              if (field.Type == TType.String)
              {
                Json = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 11:
              if (field.Type == TType.List)
              {
                {
                  var _list12 = await iprot.ReadListBeginAsync(cancellationToken);
                  Array = new List<global::QueryCat.Plugins.Sdk.VariantValue>(_list12.Count);
                  for(int _i13 = 0; _i13 < _list12.Count; ++_i13)
                  {
                    global::QueryCat.Plugins.Sdk.VariantValue _elem14;
                    _elem14 = new global::QueryCat.Plugins.Sdk.VariantValue();
                    await _elem14.ReadAsync(iprot, cancellationToken);
                    Array.Add(_elem14);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 12:
              if (field.Type == TType.List)
              {
                {
                  var _list15 = await iprot.ReadListBeginAsync(cancellationToken);
                  Map = new List<global::QueryCat.Plugins.Sdk.MapEntry>(_list15.Count);
                  for(int _i16 = 0; _i16 < _list15.Count; ++_i16)
                  {
                    global::QueryCat.Plugins.Sdk.MapEntry _elem17;
                    _elem17 = new global::QueryCat.Plugins.Sdk.MapEntry();
                    await _elem17.ReadAsync(iprot, cancellationToken);
                    Map.Add(_elem17);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp18 = new TStruct("VariantValue");
        await oprot.WriteStructBeginAsync(tmp18, cancellationToken);
        #pragma warning disable IDE0017  // simplified init
        var tmp19 = new TField();
        if(__isset.isNull)
        {
          tmp19.Name = "isNull";
          tmp19.Type = TType.Bool;
          tmp19.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
          await oprot.WriteBoolAsync(IsNull, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.@integer)
        {
          tmp19.Name = "integer";
          tmp19.Type = TType.I64;
          tmp19.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
          await oprot.WriteI64Async(Integer, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((String != null) && __isset.@string)
        {
          tmp19.Name = "string";
          tmp19.Type = TType.String;
          tmp19.ID = 3;
          await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
          await oprot.WriteStringAsync(String, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.@float)
        {
          tmp19.Name = "float";
          tmp19.Type = TType.Double;
          tmp19.ID = 4;
          await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
          await oprot.WriteDoubleAsync(Float, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.@timestamp)
        {
          tmp19.Name = "timestamp";
          tmp19.Type = TType.I64;
          tmp19.ID = 5;
          await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
          await oprot.WriteI64Async(Timestamp, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.@boolean)
        {
          tmp19.Name = "boolean";
          tmp19.Type = TType.Bool;
          tmp19.ID = 6;
          await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
          await oprot.WriteBoolAsync(Boolean, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Decimal != null) && __isset.@decimal)
        {
          tmp19.Name = "decimal";
          tmp19.Type = TType.Struct;
          tmp19.ID = 7;
          await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
          await Decimal.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.@interval)
        {
          tmp19.Name = "interval";
          tmp19.Type = TType.I64;
          tmp19.ID = 8;
          await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
          await oprot.WriteI64Async(Interval, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Object != null) && __isset.@object)
        {
          tmp19.Name = "object";
          tmp19.Type = TType.Struct;
          tmp19.ID = 9;
          await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
          await Object.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Json != null) && __isset.@json)
        {
          tmp19.Name = "json";
          tmp19.Type = TType.String;
          tmp19.ID = 10;
          await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
          await oprot.WriteStringAsync(Json, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Array != null) && __isset.@array)
        {
          tmp19.Name = "array";
          tmp19.Type = TType.List;
          tmp19.ID = 11;
          await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Array.Count), cancellationToken);
          foreach (global::QueryCat.Plugins.Sdk.VariantValue _iter20 in Array)
          {
            await _iter20.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Map != null) && __isset.@map)
        {
          tmp19.Name = "map";
          tmp19.Type = TType.List;
          tmp19.ID = 12;
          await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Map.Count), cancellationToken);
          foreach (global::QueryCat.Plugins.Sdk.MapEntry _iter21 in Map)
          {
            await _iter21.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        #pragma warning restore IDE0017  // simplified init
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not VariantValue other) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.isNull == other.__isset.isNull) && ((!__isset.isNull) || (global::System.Object.Equals(IsNull, other.IsNull))))
        && ((__isset.@integer == other.__isset.@integer) && ((!__isset.@integer) || (global::System.Object.Equals(Integer, other.Integer))))
        && ((__isset.@string == other.__isset.@string) && ((!__isset.@string) || (global::System.Object.Equals(String, other.String))))
        && ((__isset.@float == other.__isset.@float) && ((!__isset.@float) || (global::System.Object.Equals(Float, other.Float))))
        && ((__isset.@timestamp == other.__isset.@timestamp) && ((!__isset.@timestamp) || (global::System.Object.Equals(Timestamp, other.Timestamp))))
        && ((__isset.@boolean == other.__isset.@boolean) && ((!__isset.@boolean) || (global::System.Object.Equals(Boolean, other.Boolean))))
        && ((__isset.@decimal == other.__isset.@decimal) && ((!__isset.@decimal) || (global::System.Object.Equals(Decimal, other.Decimal))))
        && ((__isset.@interval == other.__isset.@interval) && ((!__isset.@interval) || (global::System.Object.Equals(Interval, other.Interval))))
        && ((__isset.@object == other.__isset.@object) && ((!__isset.@object) || (global::System.Object.Equals(Object, other.Object))))
        && ((__isset.@json == other.__isset.@json) && ((!__isset.@json) || (global::System.Object.Equals(Json, other.Json))))
        && ((__isset.@array == other.__isset.@array) && ((!__isset.@array) || (TCollections.Equals(Array, other.Array))))
        && ((__isset.@map == other.__isset.@map) && ((!__isset.@map) || (TCollections.Equals(Map, other.Map))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.isNull)
        {
          hashcode = (hashcode * 397) + IsNull.GetHashCode();
        }
        if(__isset.@integer)
        {
          hashcode = (hashcode * 397) + Integer.GetHashCode();
        }
        if((String != null) && __isset.@string)
        {
          hashcode = (hashcode * 397) + String.GetHashCode();
        }
        if(__isset.@float)
        {
          hashcode = (hashcode * 397) + Float.GetHashCode();
        }
        if(__isset.@timestamp)
        {
          hashcode = (hashcode * 397) + Timestamp.GetHashCode();
        }
        if(__isset.@boolean)
        {
          hashcode = (hashcode * 397) + Boolean.GetHashCode();
        }
        if((Decimal != null) && __isset.@decimal)
        {
          hashcode = (hashcode * 397) + Decimal.GetHashCode();
        }
        if(__isset.@interval)
        {
          hashcode = (hashcode * 397) + Interval.GetHashCode();
        }
        if((Object != null) && __isset.@object)
        {
          hashcode = (hashcode * 397) + Object.GetHashCode();
        }
        if((Json != null) && __isset.@json)
        {
          hashcode = (hashcode * 397) + Json.GetHashCode();
        }
        if((Array != null) && __isset.@array)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Array);
        }
        if((Map != null) && __isset.@map)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Map);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp22 = new StringBuilder("VariantValue(");
      int tmp23 = 0;
      if(__isset.isNull)
      {
        if(0 < tmp23++) { tmp22.Append(", "); }
        tmp22.Append("IsNull: ");
        IsNull.ToString(tmp22);
      }
      if(__isset.@integer)
      {
        if(0 < tmp23++) { tmp22.Append(", "); }
        tmp22.Append("Integer: ");
        Integer.ToString(tmp22);
      }
      if((String != null) && __isset.@string)
      {
        if(0 < tmp23++) { tmp22.Append(", "); }
        tmp22.Append("String: ");
        String.ToString(tmp22);
      }
      if(__isset.@float)
      {
        if(0 < tmp23++) { tmp22.Append(", "); }
        tmp22.Append("Float: ");
        Float.ToString(tmp22);
      }
      if(__isset.@timestamp)
      {
        if(0 < tmp23++) { tmp22.Append(", "); }
        tmp22.Append("Timestamp: ");
        Timestamp.ToString(tmp22);
      }
      if(__isset.@boolean)
      {
        if(0 < tmp23++) { tmp22.Append(", "); }
        tmp22.Append("Boolean: ");
        Boolean.ToString(tmp22);
      }
      if((Decimal != null) && __isset.@decimal)
      {
        if(0 < tmp23++) { tmp22.Append(", "); }
        tmp22.Append("Decimal: ");
        Decimal.ToString(tmp22);
      }
      if(__isset.@interval)
      {
        if(0 < tmp23++) { tmp22.Append(", "); }
        tmp22.Append("Interval: ");
        Interval.ToString(tmp22);
      }
      if((Object != null) && __isset.@object)
      {
        if(0 < tmp23++) { tmp22.Append(", "); }
        tmp22.Append("Object: ");
        Object.ToString(tmp22);
      }
      if((Json != null) && __isset.@json)
      {
        if(0 < tmp23++) { tmp22.Append(", "); }
        tmp22.Append("Json: ");
        Json.ToString(tmp22);
      }
      if((Array != null) && __isset.@array)
      {
        if(0 < tmp23++) { tmp22.Append(", "); }
        tmp22.Append("Array: ");
        Array.ToString(tmp22);
      }
      if((Map != null) && __isset.@map)
      {
        if(0 < tmp23++) { tmp22.Append(", "); }
        tmp22.Append("Map: ");
        Map.ToString(tmp22);
      }
      tmp22.Append(')');
      return tmp22.ToString();
    }
  }

}
