using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Logging;
using QueryCat.Plugins.Client;
using QueryCat.Plugins.Sdk;
using QueryCat.Backend.Core;
using QueryCat.Backend.Core.Execution;
using QueryCat.Backend.Core.Functions;
using CompletionResult = QueryCat.Plugins.Sdk.CompletionResult;
using FunctionCallArguments = QueryCat.Plugins.Sdk.FunctionCallArguments;
using FunctionCallArgumentsTypes = QueryCat.Plugins.Sdk.FunctionCallArgumentsTypes;
using LogLevel = QueryCat.Plugins.Sdk.LogLevel;
using QuestionRequest = QueryCat.Plugins.Sdk.QuestionRequest;
using QuestionResponse = QueryCat.Plugins.Sdk.QuestionResponse;
using VariantValue = QueryCat.Plugins.Sdk.VariantValue;

namespace QueryCat.Backend.ThriftPlugins;

public partial class ThriftPluginsServer
{
    [SuppressMessage("ReSharper", "InconsistentNaming", Justification = "Generated by Thrift.")]
    private sealed class Handler : QueryCatIOHandler, PluginsManager.IAsync
    {
        private readonly ThriftPluginsServer _thriftPluginsServer;
        private readonly Dictionary<int, IExecutionScope> _scopeIdToScope = new();
        private readonly Dictionary<IExecutionScope, int> _scopeToScopeId = new();
        private int _executionScopeId;

        public Handler(ThriftPluginsServer thriftPluginsServer, ObjectsStorage objectsStorage)
            : base(thriftPluginsServer._executionThread, objectsStorage)
        {
            _thriftPluginsServer = thriftPluginsServer;
        }

        /// <inheritdoc />
        public Task<RegistrationResult> RegisterPluginAsync(
            string registration_token,
            string callback_uri,
            PluginData? plugin_data,
            CancellationToken cancellationToken = default)
        {
            if (plugin_data == null)
            {
                return Task.FromResult(new RegistrationResult
                {
                    Version = Application.GetVersion(),
                    Token = -1,
                    MinLogLevel = SdkConvert.Convert(GetCurrentLogLevel()),
                });
            }

            // Validate authentication token.
            _thriftPluginsServer._logger.LogTrace(
                "Pre-register plugin '{PluginName}' ({PluginVersion}) with token '{Token}' and callback URI '{CallbackUri}'.",
                plugin_data.Name,
                plugin_data.Version,
                registration_token,
                callback_uri);
            if (!_thriftPluginsServer.SkipTokenVerification && !_thriftPluginsServer.VerifyRegistrationToken(registration_token))
            {
                if (_thriftPluginsServer._logger.IsEnabled(Microsoft.Extensions.Logging.LogLevel.Debug))
                {
                    _thriftPluginsServer._logger.LogDebug("Available tokens:\n" + _thriftPluginsServer.DumpRegistrationTokens());
                }
                throw new QueryCatPluginException(ErrorType.INVALID_REGISTRATION_TOKEN, Resources.Errors.InvalidToken);
            }

            // Create plugin context, init and add it to a list. "callback_uri" is the URI
            // provided by the client to connect to it.
            var context = CreateClientConnection(callback_uri);
            if (!string.IsNullOrEmpty(plugin_data.Name))
            {
                context.PluginName = plugin_data.Name;
            }
            if (string.IsNullOrEmpty(context.PluginName))
            {
                context.PluginName = _thriftPluginsServer.GetPluginNameByRegistrationToken(registration_token);
            }
            if (plugin_data.Functions != null)
            {
                foreach (var function in plugin_data.Functions)
                {
                    context.Functions.Add(
                        new PluginContextFunction(
                            function.Signature,
                            function.Description,
                            function.IsSafe,
                            function.IsAggregate,
                            (function.FormatterIds ?? []).ToArray()
                        )
                    );
                }
            }
            var token = _thriftPluginsServer.GenerateToken();
            _thriftPluginsServer.RegisterPluginContext(context, registration_token, token);

            // Since we registered plugin we can release semaphore and notify loader.
            _thriftPluginsServer.ConfirmRegistrationToken(registration_token);
            _thriftPluginsServer._logger.LogDebug("Registered plugin '{PluginName}'.", context.PluginName);

            return Task.FromResult(new RegistrationResult
            {
                Token = token,
                Version = Application.GetVersion(),
                MinLogLevel = SdkConvert.Convert(GetCurrentLogLevel()),
            });
        }

        /// <inheritdoc />
        public async Task PluginReadyAsync(long token, CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(PluginReadyAsync), cancellationToken);
            _thriftPluginsServer.SetPluginReady(token);
        }

        private ThriftPluginContext CreateClientConnection(string callbackUri)
        {
            var context = new ThriftPluginContext(callbackUri, _thriftPluginsServer._objectsStorage,
                maxConnections: _thriftPluginsServer._maxConnectionsToClient);
            _thriftPluginsServer._logger.LogTrace("Create plugin context, URI '{CallbackUri}'.", callbackUri);
            return context;
        }

        /// <inheritdoc />
        public async Task<VariantValue> RunQueryAsync(long token,
            string query,
            Dictionary<string, VariantValue>? parameters,
            CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(RunQueryAsync), cancellationToken);
            var @params = (parameters ?? new Dictionary<string, VariantValue>())
                .ToDictionary(k => k.Key, v => SdkConvert.Convert(v.Value));
            var result = await _thriftPluginsServer._executionThread.RunAsync(query, @params, cancellationToken);
            var resultObject = AddObjectToStorage(result);
            if (resultObject != null)
            {
                return resultObject;
            }
            return SdkConvert.Convert(result);
        }

        /// <inheritdoc />
        public async Task SetConfigValueAsync(long token, string key, VariantValue? value, CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(SetConfigValueAsync), cancellationToken);
            var internalValue = value != null ? SdkConvert.Convert(value) : Core.Types.VariantValue.Null;
            await _thriftPluginsServer._configStorage.SetAsync(key, internalValue, cancellationToken);
        }

        /// <inheritdoc />
        public async Task<VariantValue> GetConfigValueAsync(long token, string key, CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(GetConfigValueAsync), cancellationToken);
            var value = await _thriftPluginsServer._configStorage.GetAsync(key, cancellationToken);
            return SdkConvert.Convert(value);
        }

        /// <inheritdoc />
        public async Task<VariantValue> GetVariableAsync(long token, string name, CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(GetVariableAsync), cancellationToken);
            if (_thriftPluginsServer._executionThread.TopScope.TryGetVariable(name, out var value))
            {
                return SdkConvert.Convert(value);
            }
            return SdkConvert.Convert(Core.Types.VariantValue.Null);
        }

        /// <inheritdoc />
        public async Task<VariantValue> SetVariableAsync(long token, string name, VariantValue? value, CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(SetVariableAsync), cancellationToken);
            if (value == null)
            {
                return SdkConvert.Convert(Core.Types.VariantValue.Null);
            }
            _thriftPluginsServer._executionThread.TopScope.Variables[name] = SdkConvert.Convert(value);
            return value;
        }

        /// <inheritdoc />
        public async Task<List<ScopeVariable>> GetVariablesAsync(long token, int scope_id, CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(GetVariablesAsync), cancellationToken);
            if (_scopeIdToScope.TryGetValue(scope_id, out var scope))
            {
                var result = scope.Variables.Select(v => new ScopeVariable(v.Key, SdkConvert.Convert(v.Value))).ToList();
                return result;
            }
            return [];
        }

        private int AddScope(IExecutionScope scope)
        {
            if (_scopeToScopeId.TryGetValue(scope, out var scopeId))
            {
                return scopeId;
            }
            scopeId = Interlocked.Increment(ref _executionScopeId);
            _scopeIdToScope[scopeId] = scope;
            _scopeToScopeId[scope] = scopeId;
            return scopeId;
        }

        private int RemoveScope(IExecutionScope scope)
        {
            if (_scopeToScopeId.Remove(scope, out var scopeId))
            {
                _scopeIdToScope.Remove(scopeId);
                return scopeId;
            }
            return ThriftPluginExecutionScope.NoScopeId;
        }

        private int GetScopeParentId(IExecutionScope scope)
        {
            if (scope.Parent != null && _scopeToScopeId.TryGetValue(scope.Parent, out var parentScopeId))
            {
                return parentScopeId;
            }
            return ThriftPluginExecutionScope.NoScopeId;
        }

        /// <inheritdoc />
        public async Task<ExecutionScope> PushScopeAsync(long token, CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(PushScopeAsync), cancellationToken);
            var scope = _thriftPluginsServer._executionThread.PushScope();
            var scopeId = AddScope(scope);
            return new ExecutionScope(scopeId, GetScopeParentId(scope));
        }

        /// <inheritdoc />
        public async Task<ExecutionScope> PopScopeAsync(long token, CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(PopScopeAsync), cancellationToken);
            var scope = _thriftPluginsServer._executionThread.PopScope();
            if (scope != null)
            {
                var scopeId = AddScope(scope); // Do not remove it because it can be used in closure code.
                return new ExecutionScope(scopeId, GetScopeParentId(scope));
            }
            return new ExecutionScope(ThriftPluginExecutionScope.NoScopeId, ThriftPluginExecutionScope.NoScopeId);
        }

        /// <inheritdoc />
        public async Task<ExecutionScope> PeekTopScopeAsync(long token, CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(PeekTopScopeAsync), cancellationToken);
            var topScope = _thriftPluginsServer._executionThread.TopScope;
            var scopeId = AddScope(topScope);
            return new ExecutionScope(scopeId, GetScopeParentId(topScope));
        }

        /// <inheritdoc />
        public async Task<List<CompletionResult>> GetCompletionsAsync(long token, string text, int position, CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(GetCompletionsAsync), cancellationToken);
            var completions = await _thriftPluginsServer._executionThread.GetCompletionsAsync(text, position, null, cancellationToken)
                .ToListAsync(cancellationToken);
            return completions.Select(SdkConvert.Convert).ToList();
        }

        /// <inheritdoc />
        public async Task LogAsync(long token, LogLevel level, string message, List<string>? arguments,
            CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(LogAsync), cancellationToken);

            var context = _thriftPluginsServer.GetPluginContextByToken(token);
            var logLevel = SdkConvert.Convert(level);

            message = $"[{context.PluginName}] {message}";
            if (arguments != null && arguments.Count > 0)
            {
                _thriftPluginsServer._logger.Log(logLevel, message, args: arguments.Cast<object>().ToArray());
            }
            else
            {
                _thriftPluginsServer._logger.Log(logLevel, message);
            }
        }

        /// <inheritdoc />
        public async Task<Statistic> GetStatisticAsync(long token, CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(GetStatisticAsync), cancellationToken);
            var statistic = SdkConvert.Convert(_thriftPluginsServer._executionThread.Statistic);
            return statistic;
        }

        /// <inheritdoc />
        public async Task<Function> ResolveUriAsync(long token, string uri, CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(ResolveUriAsync), cancellationToken);
            var function = _thriftPluginsServer._executionThread.FunctionsManager.ResolveUri(uri);
            if (function == null)
            {
                return null!;
            }
            return CreateFunction(function);
        }

        /// <inheritdoc />
        public async Task<List<Function>> FindFunctionByNameAsync(long token, string name, FunctionCallArgumentsTypes? args_types,
            CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(ResolveUriAsync), cancellationToken);
            var functions = _thriftPluginsServer._executionThread.FunctionsManager.FindByName(name,
                SdkConvert.Convert(args_types ?? new FunctionCallArgumentsTypes())
            );
            return functions.Select(CreateFunction).ToList();
        }

        /// <inheritdoc />
        public async Task<List<Function>> GetFunctionsAsync(long token, CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(ResolveUriAsync), cancellationToken);
            var functions = _thriftPluginsServer._executionThread.FunctionsManager.GetFunctions();
            return functions.Select(CreateFunction).ToList();
        }

        private static Function CreateFunction(IFunction function)
            => new(
                FunctionFormatter.GetSignature(function, forceLowerCase: true),
                function.Description,
                function.IsAggregate)
            {
                IsSafe = function.IsSafe,
            };

        /// <inheritdoc />
        public async Task RegisterFunctionAsync(long token, List<Function>? functions, CancellationToken cancellationToken = default)
        {
            await BeforeCallAsync(token, nameof(ResolveUriAsync), cancellationToken);
            var context = _thriftPluginsServer.GetPluginContextByToken(token);
            if (functions == null)
            {
                return;
            }
            foreach (var function in functions)
            {
                context.Functions.Add(
                    new PluginContextFunction(
                        function.Signature,
                        function.Description,
                        function.IsSafe,
                        function.IsAggregate,
                        (function.FormatterIds ?? []).ToArray()
                    )
                );
            }
        }

        /// <inheritdoc />
        protected override Task BeforeCallAsync(long token, string methodName, CancellationToken cancellationToken = default)
        {
            _thriftPluginsServer.ValidateToken(token);
            return base.BeforeCallAsync(token, methodName, cancellationToken);
        }

        private Microsoft.Extensions.Logging.LogLevel GetCurrentLogLevel()
        {
            foreach (var logLevel in Enum.GetValues<Microsoft.Extensions.Logging.LogLevel>())
            {
                if (_thriftPluginsServer._logger.IsEnabled(logLevel))
                {
                    return logLevel;
                }
            }

            return Microsoft.Extensions.Logging.LogLevel.None;
        }
    }

    [SuppressMessage("ReSharper", "InconsistentNaming", Justification = "Generated by Thrift.")]
    private sealed class HandlerWithExceptionIntercept : PluginsManager.IAsync
    {
        private readonly PluginsManager.IAsync _handler;
        private readonly ILogger _logger = Application.LoggerFactory.CreateLogger(nameof(HandlerWithExceptionIntercept));

        public HandlerWithExceptionIntercept(PluginsManager.IAsync handler)
        {
            _handler = handler;
        }

        /// <inheritdoc />
        public async Task<RegistrationResult> RegisterPluginAsync(string registration_token, string callback_uri, PluginData? plugin_data,
            CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.RegisterPluginAsync(registration_token, callback_uri, plugin_data, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task PluginReadyAsync(long token, CancellationToken cancellationToken = default)
        {
            try
            {
                await _handler.PluginReadyAsync(token, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<VariantValue> CallFunctionAsync(long token, string function_name, FunctionCallArguments? call_args, int object_handle,
            CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.CallFunctionAsync(token, function_name, call_args, object_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<VariantValue> RunQueryAsync(long token, string query, Dictionary<string, VariantValue>? parameters,
            CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.RunQueryAsync(token, query, parameters, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task SetConfigValueAsync(long token, string key, VariantValue? value, CancellationToken cancellationToken = default)
        {
            try
            {
                await _handler.SetConfigValueAsync(token, key, value, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<VariantValue> GetConfigValueAsync(long token, string key, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.GetConfigValueAsync(token, key, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<VariantValue> GetVariableAsync(long token, string name, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.GetVariableAsync(token, name, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<VariantValue> SetVariableAsync(long token, string name, VariantValue? value, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.SetVariableAsync(token, name, value, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<List<ScopeVariable>> GetVariablesAsync(long token, int scope_id, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.GetVariablesAsync(token, scope_id, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<ExecutionScope> PushScopeAsync(long token, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.PushScopeAsync(token, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<ExecutionScope> PopScopeAsync(long token, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.PopScopeAsync(token, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<ExecutionScope> PeekTopScopeAsync(long token, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.PeekTopScopeAsync(token, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<List<CompletionResult>> GetCompletionsAsync(long token, string text, int position, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.GetCompletionsAsync(token, text, position, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<byte[]> Blob_ReadAsync(long token, int object_blob_handle, int offset, int count,
            CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.Blob_ReadAsync(token, object_blob_handle, offset, count, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<long> Blob_WriteAsync(long token, int object_blob_handle, byte[] bytes,
            CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.Blob_WriteAsync(token, object_blob_handle, bytes, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<long> Blob_GetLengthAsync(long token, int object_blob_handle, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.Blob_GetLengthAsync(token, object_blob_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<string> Blob_GetContentTypeAsync(long token, int object_blob_handle, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.Blob_GetContentTypeAsync(token, object_blob_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<string> Blob_GetNameAsync(long token, int object_blob_handle, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.Blob_GetContentTypeAsync(token, object_blob_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<List<Column>> RowsSet_GetColumnsAsync(long token, int object_rows_set_handle, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.RowsSet_GetColumnsAsync(token, object_rows_set_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task RowsSet_OpenAsync(long token, int object_rows_set_handle, CancellationToken cancellationToken = default)
        {
            try
            {
                await _handler.RowsSet_OpenAsync(token, object_rows_set_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task RowsSet_CloseAsync(long token, int object_rows_set_handle, CancellationToken cancellationToken = default)
        {
            try
            {
                await _handler.RowsSet_CloseAsync(token, object_rows_set_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task RowsSet_ResetAsync(long token, int object_rows_set_handle, CancellationToken cancellationToken = default)
        {
            try
            {
                await _handler.RowsSet_ResetAsync(token, object_rows_set_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task RowsSet_SetContextAsync(long token, int object_rows_set_handle, ContextQueryInfo? context_query_info,
            ContextInfo? context_info, CancellationToken cancellationToken = default)
        {
            try
            {
                await _handler.RowsSet_SetContextAsync(token, object_rows_set_handle,
                    context_query_info, context_info, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<int> RowsSet_PositionAsync(long token, int object_rows_set_handle, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.RowsSet_PositionAsync(token, object_rows_set_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<int> RowsSet_TotalRowsAsync(long token, int object_rows_set_handle, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.RowsSet_TotalRowsAsync(token, object_rows_set_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task RowsSet_SeekAsync(long token, int object_rows_set_handle, int offset, CursorSeekOrigin origin,
            CancellationToken cancellationToken = default)
        {
            try
            {
                await _handler.RowsSet_SeekAsync(token, object_rows_set_handle, offset, origin, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<RowsList> RowsSet_GetRowsAsync(long token, int object_rows_set_handle, int count,
            CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.RowsSet_GetRowsAsync(token, object_rows_set_handle, count, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<List<string>> RowsSet_GetUniqueKeyAsync(long token, int object_rows_set_handle, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.RowsSet_GetUniqueKeyAsync(token, object_rows_set_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<List<KeyColumn>> RowsSet_GetKeyColumnsAsync(long token, int object_rows_set_handle, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.RowsSet_GetKeyColumnsAsync(token, object_rows_set_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task RowsSet_SetKeyColumnValueAsync(long token, int object_rows_set_handle, int column_index, string operation,
            VariantValue? value, CancellationToken cancellationToken = default)
        {
            try
            {
                await _handler.RowsSet_SetKeyColumnValueAsync(token, object_rows_set_handle, column_index, operation, value, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task RowsSet_UnsetKeyColumnValueAsync(long token, int object_rows_set_handle, int column_index, string operation,
            CancellationToken cancellationToken = default)
        {
            try
            {
                await _handler.RowsSet_UnsetKeyColumnValueAsync(token, object_rows_set_handle, column_index, operation, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<QueryCatErrorCode> RowsSet_UpdateValueAsync(long token, int object_rows_set_handle, int column_index, VariantValue? value,
            CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.RowsSet_UpdateValueAsync(token, object_rows_set_handle, column_index, value, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<QueryCatErrorCode> RowsSet_WriteValuesAsync(long token, int object_rows_set_handle, List<VariantValue>? values,
            CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.RowsSet_WriteValuesAsync(token, object_rows_set_handle, values, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<QueryCatErrorCode> RowsSet_DeleteRowAsync(long token, int object_rows_set_handle, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.RowsSet_DeleteRowAsync(token, object_rows_set_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<ModelDescription> RowsSet_GetDescriptionAsync(long token, int object_handle, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.RowsSet_GetDescriptionAsync(token, object_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<int> RowsFormatter_OpenInputAsync(long token, int object_rows_formatter_handle, int object_blob_handle, string? key,
            CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.RowsFormatter_OpenInputAsync(token, object_rows_formatter_handle, object_blob_handle, key, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<int> RowsFormatter_OpenOutputAsync(long token, int object_rows_formatter_handle, int object_blob_handle,
            CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.RowsFormatter_OpenOutputAsync(token, object_rows_formatter_handle, object_blob_handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<QuestionResponse> AnswerAgent_AskAsync(long token, int object_answer_agent_handle, QuestionRequest? request,
            CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.AnswerAgent_AskAsync(token, object_answer_agent_handle, request, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task Thread_CloseHandleAsync(long token, int handle, CancellationToken cancellationToken = default)
        {
            try
            {
                await _handler.Thread_CloseHandleAsync(token, handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<ObjectValue> Thread_GetHandleInfoAsync(long token, int handle, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.Thread_GetHandleInfoAsync(token, handle, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<ObjectValue> Thread_GetHandleFromVariableAsync(long token, string name, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.Thread_GetHandleFromVariableAsync(token, name, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task LogAsync(long token, LogLevel level, string message, List<string>? arguments, CancellationToken cancellationToken = default)
        {
            try
            {
                await _handler.LogAsync(token, level, message, arguments, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<Statistic> GetStatisticAsync(long token, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.GetStatisticAsync(token, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<Function> ResolveUriAsync(long token, string uri, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.ResolveUriAsync(token, uri, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<List<Function>> FindFunctionByNameAsync(long token, string name, FunctionCallArgumentsTypes? args_types,
            CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.FindFunctionByNameAsync(token, name, args_types, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task<List<Function>> GetFunctionsAsync(long token, CancellationToken cancellationToken = default)
        {
            try
            {
                return await _handler.GetFunctionsAsync(token, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }

        /// <inheritdoc />
        public async Task RegisterFunctionAsync(long token, List<Function>? functions, CancellationToken cancellationToken = default)
        {
            try
            {
                await _handler.RegisterFunctionAsync(token, functions, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, Resources.Errors.HandlerInternalError);
                throw QueryCatPluginExceptionUtils.Create(ex);
            }
        }
    }
}
